<?php
    $_REQUEST['skip_cookie']=true;
    require_once '../includes.php';
    Delete()->from('corsi_planning_spostati')->where("id_corsi_planning={$_REQUEST['id']}");
    if(isset($_REQUEST['delete'])){
        $save=[
            'id_corsi_planning'=>$_REQUEST['id'],
            'data'=>$_REQUEST['data']
        ];
    }
    else{
        $save=[
            'id_corso'=>$_REQUEST['id_corso'],
            'id_corsi_planning'=>$_REQUEST['id'],
            'row_inizio'=>$_REQUEST['row_inizio'],
            'row_fine'=>$_REQUEST['row_fine'],
            'id_terapista'=>$_REQUEST['id_terapista'],
            'data'=>$_REQUEST['data']
        ];
    }
    Insert($save)->into('corsi_planning_spostati');