<style>
    body {
  font-family: Arial, sans-serif;
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 50px;
}

.time-picker {
  display: flex;
  align-items: center;
  gap: 10px;
}

.scroller {
  width: 60px;
  height: 100px;
  overflow-y: auto;
  scroll-behavior: smooth;
  text-align: center;
  border: 1px solid #ccc;
  border-radius: 8px;
}

.scroll-content div {
  padding: 10px;
  font-size: 1.5em;
}

.scroll-content div.selected {
  background-color: #007bff;
  color: #fff;
  border-radius: 4px;
}

.separator {
  font-size: 2em;
}

</style>
<div class="time-picker">
  <div class="scroller" id="hourScroller">
    <div class="scroll-content">
      <!-- Hour values generated by JavaScript -->
    </div>
  </div>
  <span class="separator">:</span>
  <div class="scroller" id="minuteScroller">
    <div class="scroll-content">
      <!-- Minute values generated by JavaScript -->
    </div>
  </div>
</div>
<p>Selected Time: <span id="selectedTime">00:00</span></p>
<script>
    const hourScroller = document.getElementById("hourScroller").querySelector(".scroll-content");
const minuteScroller = document.getElementById("minuteScroller").querySelector(".scroll-content");
const selectedTime = document.getElementById("selectedTime");

function createOptions(container, count, type) {
  for (let i = 0; i < count; i++) {
    const option = document.createElement("div");
    option.textContent = i.toString().padStart(2, "0");
    option.classList.add("option");
    option.addEventListener("click", () => {
      selectOption(container, option, type);
    });
    container.appendChild(option);
  }
}

function selectOption(container, option, type) {
  container.querySelectorAll("div").forEach(div => div.classList.remove("selected"));
  option.classList.add("selected");

  updateSelectedTime(type, option.textContent);
}

let time = { hour: "00", minute: "00" };

function updateSelectedTime(type, value) {
  time[type] = value;
  selectedTime.textContent = `${time.hour}:${time.minute}`;
}

createOptions(hourScroller, 24, "hour");
createOptions(minuteScroller, 60, "minute");

</script>